apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  replicas: 3
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels: {}
              topologyKey: kubernetes.io/hostname
      initContainers:
      - name: configure-radicale
        image: mirror.gcr.io/dibi/envsubst
        command: 
          - sh
          - -c
          - envsubst < /template/config.tmpl > /etc/radicale/config
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgresql01-user-radicale
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql01-user-radicale
                key: password
          - name: LDAP_BIND_DN
            valueFrom:
              secretKeyRef:
                name: bottin-admin
                key: username
          - name: LDAP_BIND_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bottin-admin
                key: password
        volumeMounts:
        - name: template
          mountPath: /template
        - name: config
          mountPath: /etc/radicale
      containers:
        - name: radicale
          image: ghcr.io/teapotovh/radicale:v0.0.17
          ports:
            - name: http
              containerPort: 5232
          volumeMounts:
            - name: config
              mountPath: /etc/radicale
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: template
          configMap:
            name: config
        - name: config
          emptyDir: {}
