apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
spec:
  interval: 5m
  path: infra/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: prod
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuers
spec:
  interval: 5m
  path: infra/cert-manager/issuers
  dependsOn:
    - name: cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: prod
