apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
spec:
  interval: 5m
  path: infra/cloudnative-pg
  prune: true
  dependsOn:
    - name: local-path-provisioner
  sourceRef:
    kind: GitRepository
    name: prod
