apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: descheduler
spec:
  interval: 5m
  path: infra/descheduler
  prune: true
  sourceRef:
    kind: GitRepository
    name: prod
