apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-crd
spec:
  interval: 1h
  path: infra/envoy-gateway/crd
  prune: true
  dependsOn:
    - name: gateway-api
  sourceRef:
    kind: GitRepository
    name: prod
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway
spec:
  interval: 1h
  path: infra/envoy-gateway
  prune: true
  dependsOn:
    - name: gateway-api
    - name: envoy-gateway-crd
  sourceRef:
    kind: GitRepository
    name: prod
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-cert
spec:
  interval: 1h
  path: infra/envoy-gateway/cert
  prune: true
  dependsOn:
    - name: envoy-gateway
  sourceRef:
    kind: GitRepository
    name: prod
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-gateway
spec:
  interval: 1h
  path: infra/envoy-gateway/gateway
  prune: true
  dependsOn:
    - name: envoy-gateway
  sourceRef:
    kind: GitRepository
    name: prod

