apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
spec:
  interval: 5m
  path: infra/external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: prod
