apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns-crd
spec:
  interval: 1h
  path: infra/external-dns/crd
  prune: true
  sourceRef:
    kind: GitRepository
    name: prod
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
spec:
  interval: 1h
  path: infra/external-dns
  prune: true
  dependsOn:
    - name: external-dns-crd
    - name: sealed-secrets
  suspend: true # TODO: re-enable external-dns
  sourceRef:
    kind: GitRepository
    name: prod
