apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path-provisioner
spec:
  interval: 5m
  path: infra/local-path-provisioner
  prune: true
  sourceRef:
    kind: GitRepository
    name: prod
