apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
spec:
  interval: 5m
  path: infra/metrics-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: prod
