apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: reflector
spec:
  interval: 5m
  path: infra/reflector
  prune: true
  sourceRef:
    kind: GitRepository
    name: prod
