apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets-crd
spec:
  interval: 1h
  path: infra/sealed-secrets/crd
  prune: true
  sourceRef:
    kind: GitRepository
    name: prod
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
spec:
  interval: 1h
  path: infra/sealed-secrets
  prune: true
  dependsOn:
    - name: sealed-secrets-crd
  sourceRef:
    kind: GitRepository
    name: prod
