namespace: app
namePrefix: kontakte-

labels:
  - includeSelectors: true
    pairs:
      app: kontakte
      app.kubernetes.io/name: kontakte
      app.kubernetes.io/part-of: kontakte
      app.kubernetes.io/managed-by: kustomize

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secret.yaml
