apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secrets
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    jwt: AgBDi+CgFcMfFkQ8+mLFxAg7MIo+yMH0hDeeeinwo5ly9X13IplMY0g7RZ5B7tZ7uMz0yHX2GwPwM7NQ2Bhqz3gfPLU4y9aHeUdW3Y4quRXBozgFGnpIp4UtN0OBWN49TY/4HsW+XwYnj1INwX/nJ97dP+xZZ8VcOiaEwcmm8x5jXoUSEuMgXpMXWMkk7EG/ndFuec+Svo4OQxEyyBnuP4D5tWw9J/hoc17don9jKVQq+ellG5qPOLOm4nT/2o3H4RIH60xKEKU90QTMTVja2a6LcJGhMu8JyJbhpMDnU6e69G9fDtWUriceagMVYfN2cC6nzfKMNzYrFwnK9nd2qc4w1AkH979zXTw2XN7qh3SCBZ6cbmBHk4GTh5CRtumtYmOvenGAn+W3wjJdDEJMsYVzW5HazrKYQaFQKqpLlWXdptUF17TK/kd92dhbgJhjaT1mYL4MMDxyummfAbWZ9npIyWI5PVLkJYvW5CHFtaF3kjr7llj7CySp0gx7+0vmCZYmQSHx+HPdEqvlYN1e4aw0bCzMYXATHr3oeZy2g1SexGKwofv4VdT3/tYSNP5v7UHEVHkbdhJwPCcx5VomXAcNU7x6OGYCAZ6nxfh6scl2qbBQeUQG0wU1h8jCB8oc1s4AcsDeQ+mb14x5kHEeX65N83uosQZGB6oKbTtV0pZGhvn6ycvbtczWB0WNm+DXuvhIF1DFyK1fS7hGvywikLI6nd+e1nQedrbED/rxR9+TxA==
