apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  "defaults.ini": |
    [auth]
    [auth.generic_oauth]
    name = OAuth
    icon = signin
    enabled = true
    allow_sign_up = true
    auto_login = false
    client_id = some_id
    client_secret =
    scopes = user:email
    empty_scopes = false
    email_attribute_name = email:primary
    email_attribute_path =
    login_attribute_path =
    name_attribute_path =
    role_attribute_path =
    role_attribute_strict = false
    org_attribute_path =
    org_mapping =
    groups_attribute_path =
    id_token_attribute_name =
    team_ids_attribute_path =
    auth_url =
    token_url =
    api_url =
    signout_redirect_url =
    teams_url =
    allowed_domains =
    allowed_groups =
    team_ids =
    allowed_organizations =
    tls_skip_verify_insecure = false
    tls_client_cert =
    tls_client_key =
    tls_client_ca =
    use_pkce = false
    auth_style =
    allow_assign_grafana_admin = false
    skip_org_role_sync = false
    use_refresh_token = false
    validate_id_token = false
    jwk_set_url =
