apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: controller
subjects:
- kind: ServiceAccount
  name: controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
  name: admission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admission
subjects:
- kind: ServiceAccount
  name: admission
