apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sendmail
spec:
  interval: 1h
  path: app/sendmail
  prune: true
  dependsOn:
    - name: app
    - name: external-dns-crd
  sourceRef:
    kind: GitRepository
    name: prod
