apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pooler
spec:
  instances: 3
  cluster:
    name: postgresql01-cluster
  type: rw
  pgbouncer:
    poolMode: session
    parameters:
      max_client_conn: "100"
      default_pool_size: "10"
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                cnpg.io/pooler: postgresql01-pooler
            topologyKey: kubernetes.io/hostname
      containers:
      - name: pgbouncer
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 200m
            memory: 128Mi
  serviceTemplate:
    spec:
      internalTrafficPolicy: Local
