apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  template:
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      containers:
        - name: prometheus
          image: ghcr.io/teapotovh/logd:v0.0.8
          args:
            - --log-path=/logs
          volumeMounts:
            - name: logs
              mountPath: /logs
          ports:
            - name: http
              protocol: TCP
              containerPort: 8145
            - name: observability
              protocol: TCP
              containerPort: 8146
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 100m
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /livez
              port: observability
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 6
            httpGet:
              path: /readyz
              port: observability
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
      volumes:
        - name: logs
          hostPath:
            path: /var/log/teapot
