namespace: storage
namePrefix: teapot-logd-

labels:
- includeSelectors: true
  pairs:
    app: teapot-logd
    app.kubernetes.io/name: teapot-logd
    app.kubernetes.io/part-of: teapot-logd

resources:
- deployment.yaml
- service.yaml
