apiVersion: v1
kind: ServiceAccount
metadata:
  name: eg-gateway-helm-certgen
  namespace: envoy-gateway-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: 'eg-gateway-helm-certgen:envoy-gateway-system'
rules:
  - apiGroups:
    - admissionregistration.k8s.io
    resources:
    - mutatingwebhookconfigurations
    verbs:
    - get
    - list
    - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
    resourceNames:
      - 'envoy-gateway-topology-injector.envoy-gateway-system'
    verbs:
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: 'eg-gateway-helm-certgen:envoy-gateway-system'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'eg-gateway-helm-certgen:envoy-gateway-system'
subjects:
  - kind: ServiceAccount
    name: 'eg-gateway-helm-certgen'
    namespace: envoy-gateway-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eg-gateway-helm-certgen
  namespace: envoy-gateway-system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eg-gateway-helm-certgen
  namespace: envoy-gateway-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'eg-gateway-helm-certgen'
subjects:
- kind: ServiceAccount
  name: 'eg-gateway-helm-certgen'
  namespace: envoy-gateway-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: eg-gateway-helm-certgen
  namespace: envoy-gateway-system
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: certgen
    spec:
      containers:
      - command:
        - envoy-gateway
        - certgen
        env:
        - name: ENVOY_GATEWAY_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: cluster.local
        image: mirror.gcr.io/envoyproxy/gateway:v1.8.0
        imagePullPolicy: IfNotPresent
        name: envoy-gateway-certgen
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
          seccompProfile:
            type: RuntimeDefault
      imagePullSecrets: []
      restartPolicy: Never
      serviceAccountName: eg-gateway-helm-certgen
  ttlSecondsAfterFinished: 30
---
