apiVersion: v1
kind: Service
metadata:
  name: controller
  labels:
    control-plane: envoy-gateway
spec:
  type: ClusterIP
  selector:
    control-plane: envoy-gateway
  ports:
  - name: grpc
    port: 18000
    targetPort: 18000
  - name: ratelimit
    port: 18001
    targetPort: 18001
  - name: wasm
    port: 18002
    targetPort: 18002
  - name: metrics
    port: 19001
    targetPort: 19001
  - name: webhook
    port: 9443
    targetPort: 9443
