apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    token: AgBmi1BTR+/2cilQtKHPDt7JeruR8E/xwbu5B14xfDW4bXWzFvcxbkP3bN82q4u3Lah4YQa+D5o5oGUfj87e8VLQR/ygNPJNPnGu5oTYuatmxFbQV+ZtbkkpgTAyjJR+XiH4BbpqsSNgxQNQWRrH66HUi2JvMpWBKoZZxnTTAObDUFvCBausDCMFVHrrvVUfeMcnQmIzafCo34tRByCoxGIivg6sCMdQsUIg0Rn4yx49zZJgdX4qfZpkEsz6hvF/Sq8mnYjxLTOoQwoyE3devtVIOOGYBs+D0TZaioH1fkPA6ARlezD40Vn/cE/Upeu8EZ8XA9+8A5x1om7ZlY7ZxjXhyIzdfJVVC0P8/IkYhRwcQvIKsF3nQaoM0y6qmN0gFVUTONq3tz6XN6nx22s3eoUVAyFdzksALzdTD/PUrXFpwyf+nTRTGxNB1TZ2sxb8gVibvKeprxXMhUlYhcC92J2FPg/pgT6r5euU7IyMY4o7U23ZAadceRREk9E4N3oX4YF9JBQamXfndVRTyQDwLnN54i1vnOlH7QhbBRLJQc5ACdmip1WRWo5tQBp5PlrQQtfDzz4m3k0lj5zEoznIaZg5ysq3gfD7GZeaMMDh2G/3tFwhTfZ0iyiQs1veP6RnHjwb5lz56Es6yTid9xh7+w5fIDWqAYxz+6Jb00PdWGcBN2yJCXlaZDAv1peNy9Kc01P0dUKYno7KG/tE3dwWQRlWbHxEQowEBzgjJv0e5E3f9hcjwnOevqUM
