apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: app-proxy
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDaemonSet:
        container:
          image: mirror.gcr.io/envoyproxy/envoy:distroless-v1.38.0
      envoyService:
        type: NodePort
        # internalTrafficPolicy: Local
        # externalTrafficPolicy: Local
