apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
spec:
  interval: 5m
  path: infra/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: prod
