apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    rpcSecret: AgAxhiAnIrBNVlX5iJ6UnBigBXIQzcSYv8hBhU27SyLFeFov+iovGRjAr+LglHwk0j4EW7yQRcA2n3+nFLyV6VjgHCYwmM2WQbYe2nO9OxBrcaabX/vBXH/2CFKGcVFCIpWlAL799PcsYCuRl/jNw+PtxhIxS0t29KXowuDmrwoEvKqr3bFNMkkY4ChEH/bUGxRUovgT+A3O0uwyjFBcYVPVXQZ4Uqqb6BA+7PoFHRrY5g0vcfxUbs83TXiEGKmZPKfYDanLFCXeZdinm0Ky5mriwOOyZwrsJoDuZ3DYjvDoLm1VP7rVKp56ghD18IO0kex6gsJktaapfgNmYktwsdrcreHhf80Biza9MfjMQAaG1hiSRgbSUalPRmtjgmfsEvaZbFdvAWI/YPNejkvG53zKJvyz7lSiFBShuW2Ncem8V69rE5mgSc9oWODo+2zmw4LBDnpvr7/Jcg6DRGmT/CVAdDwkfnx4GY+nLcQGwMMxPaj/z5G8JY069dJOcZ4kZlYQnSDlfTn6KGNtokly9ruFPlp3JHR5MqyqAPE75fRi7cZClrFmQZIvkNXBZesyt3gHJA2bx1ptz96hmB5b8gcVqdWfmmL7KcZdiIn3RayKSh3b804hYLKXKDP/pzUGsm9YEtRTraUQFSZWdXMJAfZNV/kcva8CNrjaPn9R+H1sbpnqzbkOLNIyZTRb54ExMbceI5WQXLz96MDbp1iZbmYcvhJdrY1p8LT716OslSXzlcvkW30OZV3wo/Eye27pXQveBPRLBmQ2ddAmTFSQYZw5
