apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: secret
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    rpcSecret: AgAUTco7s4sm0jvO2JpkgXSMLQ6/8L0iVORqIVkXkSzLQBMTXrNkW02QXvMwhGqk/ovLHyfcQf2KKTVr+MaKLJyUF6p2wae8VMkaFFi+B15ZNCObHi14M/C6gCgP0dkilLbIltV+oKeM5yoIvdB1lZ7WuPXY6hZXuLaBhH+0bnYk9qd15gGHQn+sUODa3W2tJTsn09H9eHztLy+GzRzghNG3aDlwqhA1YoJ8XvbKFZc6Ghx/7+TcE35JcObjpZOrrdIdgHgVp4kw0vMTefT5Uslu7tv/T/RJtfO47TkanVABxve2+9qlqHCK1rZnmruWONYdGVXToZvHEN+s3BrNsKz6plKqqU6s/I17QPaNZyfp4SoJz3hD5huDypah8fmXRfB1N0FtOcyaSug/gv4yEwKRuuGWywQfoRLQ57yoRkfo9V+lUsV7nTlhGF0RSNC1IMbhTPsLlGxxY2/PQnppSjNrhd9iNqOFze3iqsE3x7SE4bTBxQQzXz+AiVTcc/mkiF9kuyngDTfIwMCc9Fv1N0zNAUVEz7BRrbkqTkTMVtL8EBBqwaeKEfJ/yXB4gpLAl9J29ec8WVV2EQnCa9RiIRCUQA5c7sC9cw70NEVXWXXjb+lPqOCPKk2MALqDfHMHtnrUlv0YCuwXI2jvqPT/i5NVl4v8IQLbhc2U/yuibRdd65/fQ4MwMB00HavSMGvR12pQa8u8QW1xh7FqP5ChOvWkjP93wadMVPSlMQBmklTIpgKOSgzF/d4dNWiBXQi+BQPBg2jNLNhpKeiOA2EImoPA
