apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: garage
spec:
  replicas: 3
  serviceName: garage
  podManagementPolicy: OrderedReady
  template:
    spec:
      serviceAccountName: serviceaccount
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: garage
            app.kubernetes.io/instance: garage01
      initContainers:
        # Copies garage.toml from configmap to temporary etc volume and replaces RPC secret placeholder
        - name: garage-init
          image: mirror.gcr.io/dibi/envsubst
          command: |
            envsubst < /mnt/garage.toml > /mnt/etc/garage.toml
          env:
            - name: RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: garage01-secret
                  key: rpcSecret
          volumeMounts:
            - name: configmap
              mountPath: /mnt/garage.toml
              subPath: garage.toml
            - name: etc
              mountPath: /mnt/etc
      containers:
        - name: garage
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          image: mirror.gcr.io/dxflrs/amd64_garage:v2.2.0
          ports:
            - containerPort: 3900
              name: s3
            - containerPort: 3903
              name: admin
          volumeMounts:
            - name: meta
              mountPath: /mnt/meta
            - name: data
              mountPath: /mnt/data
            - name: etc
              mountPath: /etc/garage.toml
              subPath: garage.toml
          resources:
            {}
      volumes:
        - name: configmap
          configMap:
            name: config
        - name: etc
          emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: meta
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path-storageclass"
      resources:
        requests:
          storage: "4Gi"
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path-storageclass"
      resources:
        requests:
          storage: "16Gi"
